ALTER TABLE refunds ADD COLUMN resolution_note VARCHAR(500);
ALTER TABLE refunds ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

-- REFUND_MANUALLY_RESOLVED (24 ky tu) vuot qua VARCHAR(20) cu.
ALTER TABLE refunds ALTER COLUMN status TYPE VARCHAR(30);
